Refactored deploy of release, prerelease and modulefiles after the renaming of the environment variables in the Gadi GitHub Environment

diff --git a/.github/workflows/update-module.yml b/.github/workflows/update-module.yml
--- a/.github/workflows/update-module.yml
+++ b/.github/workflows/update-module.yml
@@ -28,6 +28,10 @@ jobs:
       matrix:
         deployment-sites: ${{ fromJson(needs.get-deployment-sites.outputs.deployment-sites) }}
     environment: ${{ matrix.deployment-sites }}
+    env:
+      INPUT_DIR: modules
+      OUTPUT_DIR: release/modules
+      OUTPUT_DIR_PRERELEASE: prerelease/modules
     steps:
       - uses: actions/checkout@v4
 
@@ -37,23 +41,54 @@ jobs:
           hosts: |
             ${{ secrets.HOST_DATA }}
           private-key: ${{ secrets.SSH_KEY }}
-
+      
+      - name: Set deployment directories
+        run: |
+            echo "MODULE_DEPLOYMENT_DIR=${{ vars.ROOT_DIR }}/${{vars.MODULES_DIR}}/${{vars.MODULE_NAME}}" >> $GITHUB_ENV
+            echo "APP_DEPLOYMENT_DIR=${{ vars.ROOT_DIR }}/${{vars.APPS_DIR}}/${{vars.MODULE_NAME}}" >> $GITHUB_ENV
+            echo "MODULE_DEPLOYMENT_DIR_PRERELEASE=${{ vars.ROOT_DIR_PRERELEASE }}/${{vars.MODULES_DIR}}/${{vars.MODULE_NAME}}" >> $GITHUB_ENV
+            echo "APP_DEPLOYMENT_DIR_PRERELEASE=${{ vars.ROOT_DIR_PRERELEASE }}/${{vars.APPS_DIR}}/${{vars.MODULE_NAME}}" >> $GITHUB_ENV
+      
       - name: Generate release modulesfiles
         run: |
-          mkdir -p release/modules
-          sed 's|{{MODULE_DIR}}|'"${{ vars.MODULE_DIR }}"'|g' modules/.common > release/modules/.common
-          sed 's|{{APPS_DIR}}|'"${{ vars.APPS_DIR }}"'|g' modules/env.sh > release/modules/env.sh
-          chmod +x release/modules/env.sh
+          mkdir -p ${{ env.OUTPUT_DIR }}
+          sed "s|{{MODULE_DIR}}|$MODULE_DEPLOYMENT_DIR|g" ${{env.INPUT_DIR}}/.common > ${{env.OUTPUT_DIR}}/.common
+          sed 's|{{APPS_DIR}}|$APP_DEPLOYMENT_DIR|g' ${{env.INPUT_DIR}}/env.sh > ${{env.OUTPUT_DIR}}/env.sh
+          chmod +x ${{ env.OUTPUT_DIR }}/env.sh
 
-      - name: Create deployment directory on ${{ matrix.deployment-sites }}
+      - name: Copy release modulefiles to Gadi
         run: |
-          ssh ${{ secrets.USER }}@${{ secrets.HOST_DATA }} -i ${{ steps.ssh.outputs.private-key-path }} /bin/bash <<'EOT'
-          mkdir -p ${{ vars.MODULE_DIR }}
+          # Create module deployment directory
+          ssh ${{ secrets.USER }}@${{ secrets.HOST_DATA }} -i ${{ steps.ssh.outputs.private-key-path }} /bin/bash <<EOT
+          mkdir -p "$MODULE_DEPLOYMENT_DIR"
           EOT
-
-      - name: Copy modulefiles to Gadi
-        run: |
+          if [ $? -ne 0 ]; then
+            echo "Failed to create module deployment release directory"
+            exit 1
+          fi
           # Rsync release modulefiles
           rsync -rvp -e 'ssh -i ${{ steps.ssh.outputs.private-key-path }}' \
-            release/modules/ \
-            ${{ secrets.USER }}@${{ secrets.HOST_DATA }}:${{ vars.MODULE_DIR }}
+            ${{ env.OUTPUT_DIR }}/ \
+            ${{ secrets.USER }}@${{ secrets.HOST_DATA }}:${MODULE_DEPLOYMENT_DIR}
+      
+      - name: Generate prerelease modulesfiles
+        run: |
+          mkdir -p ${{ env.OUTPUT_DIR_PRERELEASE }}
+          sed "s|{{MODULE_DIR}}|$MODULE_DEPLOYMENT_DIR_PRERELEASE|g" ${{env.INPUT_DIR}}/.common > ${{env.OUTPUT_DIR_PRERELEASE}}/.common
+          sed 's|{{APPS_DIR}}|$APP_DEPLOYMENT_DIR_PRERELEASE|g' ${{env.INPUT_DIR}}/env.sh > ${{env.OUTPUT_DIR_PRERELEASE}}/env.sh
+          chmod +x ${{ env.OUTPUT_DIR_PRERELEASE }}/env.sh
+
+      - name: Copy prerelease modulefiles to Gadi
+        run: |
+          # Create module deployment directory
+          ssh ${{ secrets.USER }}@${{ secrets.HOST_DATA }} -i ${{ steps.ssh.outputs.private-key-path }} /bin/bash <<EOT
+          mkdir -p "$MODULE_DEPLOYMENT_DIR_PRERELEASE"
+          EOT
+          if [ $? -ne 0 ]; then
+            echo "Failed to create module deployment prerelease directory"
+            exit 1
+          fi
+          # Rsync prerelease modulefiles
+          rsync -rvp -e 'ssh -i ${{ steps.ssh.outputs.private-key-path }}' \
+            ${{ env.OUTPUT_DIR_PRERELEASE }}/ \
+            ${{ secrets.USER }}@${{ secrets.HOST_DATA }}:${MODULE_DEPLOYMENT_DIR_PRERELEASE}
